"""
Difference Gradient Analysis automated alignment module
"""
import numpy as np
from collections.abc import Callable
from misalign.model.image import MISImage
from misalign.model.relation import MISRelation
import misalign.canvas.canvas_rectangular as cr
from matplotlib import pyplot as plt
from matplotlib import colors

#DONE transfer past work from `feature_diff_grad_alignment` branch
#DONE update past work to be compatible with misalign 2
#TODO update docstrings to be in-line with standards
#TODO add DGA example to notebooks
#TODO create relation/project interfaces as well as raw interfaces

def metric_squared_mean(difference_array:np.ndarray)->float:
    return np.mean(difference_array**2)
def metric_absolute_mean(difference_array:np.ndarray)->float:
    return np.mean(np.abs(difference_array))

def axis_span(OVn:int,an_max:int,bn_max:int):
    """Takes the offset vector of axis n, image a max value for axis n, and image b max value for axis n. Returns image a and image b overlap spans for axis n."""
    if OVn==0:
        an_span=(0,min(an_max,bn_max))
        bn_span=(0,min(an_max,bn_max))
    elif OVn > 0:
        an_span=(0,an_max-OVn)
        bn_span=(OVn,an_max)
    elif OVn < 0:
        an_span=(-OVn,bn_max)
        bn_span=(0,bn_max+OVn)
    else:
        raise ValueError()
    return an_span,bn_span

def overlap_spans(offset_vector:tuple|np.ndarray,a_shape:tuple,b_shape:tuple):
    """Takes an offset vector and shape of image a and image b. Returns the overlapping spans.
    - Offset vector x,y
    - Shapes row,column (y,x)"""
    if not all([offset_vector[0]>-b_shape[1], # valid in -x (b to the left of a)
                offset_vector[0]<a_shape[1], # valid in +x (a to the left of b)
                offset_vector[1]>-b_shape[0], # valid in -y (b above a)
                offset_vector[1]<a_shape[0]]): # valid in +y (a above b)
        raise ValueError("These images do not overlap")
    ax_span,bx_span=axis_span(offset_vector[0],a_shape[1],b_shape[1])
    ay_span,by_span=axis_span(offset_vector[1],a_shape[0],b_shape[0])

    # # All values in spans must be greater than 0
    # if np.any(np.concat([ax_span,bx_span,ay_span,by_span])<0):
    #     raise ValueError("These images do not overlap")
    # Each value in span cannot be greater than or equal to the shape size.
    # if np.any([max(ax_span)>=a_shape[1],
    #                 max(ay_span)>=a_shape[0],
    #                 max(bx_span)>=b_shape[1],
    #                 max(by_span)>=b_shape[0],]):
    #     raise ValueError("These images do not overlap")

    return (ax_span,ay_span),(bx_span,by_span)

def difference_compare(
        image_a_array:np.ndarray,
        image_b_array:np.ndarray,
        offset_ab:tuple|np.ndarray,
        metric:Callable[[np.ndarray],float],
        return_difference=False)->float|tuple[float,np.ndarray]:
    """Compares difference of Image A and Image B using specified A-to-B relation and comparison metric.
    - `image_a` and `image_b` are numpy arrays from PIL images converted to type `int`
    - `offset_ab` is an (x,y) offset pair as generated by `MisFile.get_rels('r')`
    - `metric` can be either a string referencing a built-in metric(`diff_abs_mean`,`diff_squared_mean`) or a function of the form `metric_function(difference_array)->float`
    - Returns a float value representing the difference according to the metric
    - `return_difference` changes output to (difference_value,difference_array)
    """
    ## Find overlap spans
    try:
        a_spans,b_spans=overlap_spans(offset_ab,image_a_array.shape,image_b_array.shape)
    except ValueError:
        return float('nan')
    ## Take difference of overlaps
    difference_array=image_a_array[a_spans[1][0]:a_spans[1][1],a_spans[0][0]:a_spans[0][1]] - image_b_array[b_spans[1][0]:b_spans[1][1],b_spans[0][0]:b_spans[0][1]]
    ## Get difference metric
    difference_metric=metric(difference_array)
    ## Return of values
    if return_difference:
        return difference_metric, difference_array
    else:
        return difference_metric

def strategy_scaled_grid(
        image_a_array:np.ndarray,
        image_b_array:np.ndarray,
        rectangular_relation:tuple[int,int],
        strategy_grid_scale:int,
        strategy_max_size:int=5,
        metric:Callable[[np.ndarray],float]=metric_squared_mean,)->dict:
    grid_shape=(1+strategy_max_size*2,1+strategy_max_size*2)
    grid=np.fromfunction(lambda x,y: np.array([rectangular_relation[0]+(strategy_grid_scale*(x-strategy_max_size)),
                                                                                            rectangular_relation[1]+(strategy_grid_scale*(y-strategy_max_size))]),
                                                                                            shape=grid_shape,dtype=int)
    grid_results=np.full(grid_shape,np.nan)
    grid_indeces=np.fromfunction(lambda row,col: np.array([row,col]),shape=grid_shape,dtype=int).reshape(2,-1)

    for i,grid_index in enumerate(grid_indeces.T):
        check_offset=grid[:,grid_index[0],grid_index[1]]
        grid_results[grid_index[0],grid_index[1]]=difference_compare(image_a_array,image_b_array,
            offset_ab=check_offset,
            metric=metric)
    optimized_location=grid_results.reshape(-1).argmin()
    optimized_offset=tuple([int(value) for value in grid[:,grid_indeces[0][optimized_location],grid_indeces[1][optimized_location]]])
    return {
        "grid":grid,
        "grid_results":grid_results,
        "optimized_offset":optimized_offset,
        "initial_offset":rectangular_relation
        }
def strategy_full_grid(
        image_a_array:np.ndarray,
        image_b_array:np.ndarray,
        rectangular_relation:tuple[int,int],
        strategy_max_size:int=5,
        metric:Callable[[np.ndarray],float]=metric_squared_mean,)->dict:
    return strategy_scaled_grid(image_a_array=image_a_array,
                                image_b_array=image_b_array,
                                rectangular_relation=rectangular_relation,
                                strategy_grid_scale=1,
                                strategy_max_size=strategy_max_size,
                                metric=metric)

def filter_simple(image:cr.array_like)->np.ndarray:
    return np.asarray(image).astype(np.int16)
def filter_rgb_gray(image:cr.array_like)->np.ndarray:
    return np.mean(image,axis=-1).astype(np.int16)

def difference_gradient_analysis(
        image_a:MISImage,
        image_b:MISImage,
        relation:MISRelation,
        strategy:Callable=strategy_full_grid,
        metric:Callable[[np.ndarray],float]=metric_squared_mean,
        filter:Callable[[cr.array_like],np.ndarray]=filter_simple,
        **kwargs)->dict:
    """Compares differences of Images at multiple offsets to identify the best offset.
    - `strategy` includes `full_grid`, `local_minima`, and `gaussian_minimization`.
        - `full_grid` - search is performed from `relation`-`strategy_max` to `relation`+`strategy_max` > example: `strategy_max=3` will search a 7x7 offset space around the current offset.
        - TODO - `local_minima` - search starts with +1/-1 around `relation` and then moves to the observed minima and another +1/-1 is searched until a local minima is found.
        - TODO - `gaussian_minimization` - gaussian process regression is used to fit the minimization trend and efficiently reach the minimum value.
    - `metric` is pass-through parameter to `difference_compare`
    
    TODO rebuild docstring around "strategy" functions > all `strategy_` kwargs get passed to strategy, any `metric_` kwargs get passed to metric. etc.
    """
    ## Get image arrays
    image_a_array:np.ndarray=filter(image_a)
    image_b_array:np.ndarray=filter(image_b)

    ## Get initial relation
    initial_rectangular_relation=relation.get_relation('r')

    return strategy(image_a_array=image_a_array,
            image_b_array=image_b_array,
            rectangular_relation=initial_rectangular_relation,
            metric=metric,
            **kwargs)

# Plotting & visualizing of DGA results

def plot_grid_result(
        dga_grid_results:dict,
        overlays=True):
    plt.imshow(dga_grid_results["grid_results"].T,
        norm=colors.LogNorm(vmin=np.nanmin(dga_grid_results["grid_results"]),
                            vmax=np.nanmax(dga_grid_results["grid_results"])),
        extent=(np.min(dga_grid_results["grid"][0])-0.5,
                np.max(dga_grid_results["grid"][0])+0.5,
                np.max(dga_grid_results["grid"][1])+0.5,
                np.min(dga_grid_results["grid"][1])-0.5,), #xmin,xmax,ymin,ymax
        )
    plt.xlabel("Rectangular X-offset")
    plt.ylabel("Rectangular Y-offset")
    plt.colorbar(label="Difference Gradient Analysis Metric")

    if overlays:
        legend=False
        if "initial_offset" in dga_grid_results:
            plt.scatter(
                x=dga_grid_results["initial_offset"][0],
                y=dga_grid_results["initial_offset"][1],
                marker="o",
                color="tab:red",
                label=f'Initial: {dga_grid_results["initial_offset"]}')
            legend=True
        if "optimized_offset" in dga_grid_results:
            plt.scatter(
                x=dga_grid_results["optimized_offset"][0],
                y=dga_grid_results["optimized_offset"][1],
                marker="X",
                color="tab:pink",
                label=f'Optimized: {dga_grid_results["optimized_offset"]}')
            legend=True
        if "initial_offset" in dga_grid_results and "optimized_offset" in dga_grid_results:
            plt.annotate("", 
                xytext=dga_grid_results["initial_offset"],
                xy=dga_grid_results["optimized_offset"],
                arrowprops=dict(arrowstyle="->",color="w"),)
        if legend:
            plt.legend()

def render_rectangular_pair(
        image_a:MISImage,
        image_b:MISImage,
        relation:tuple[int,int],
        weight=cr.weight_flat,
        return_canvas_relative_offsets=False
        ):
    origin_relative_offsets=cr.rectangular_solve(
        relations=[{"ref":(image_a.name,image_b.name),"rel":relation}],
        image_names=[image_a.name,image_b.name],
        origin=image_a.name
        )

    origin_relative_extents=cr.find_relative_extents(
        image_names=[image_a.name,image_b.name],
        origin_relative_offsets=origin_relative_offsets,
        image_shapes={image_a.name:image_a.shape,image_b.name:image_b.shape}
        )

    canvas_extents, canvas_offsets=cr.resolve_extents(origin_relative_extents)

    canvas_relative_offsets=cr.place_in_canvas(
        image_names=[image_a.name,image_b.name],
        origin_relative_offsets=origin_relative_offsets,
        canvas_extents=canvas_extents,
        canvas_offsets=canvas_offsets)

    normalizer=cr.build_normalization(
        image_arrays={image_a.name:image_a,image_b.name:image_b},
        canvas_relative_offsets=canvas_relative_offsets,
        canvas_extents=canvas_extents,
        weight=cr.weight_flat,
        )
    render=cr.render_blended(
        image_arrays={image_a.name:image_a,image_b.name:image_b},
        canvas_relative_offsets=canvas_relative_offsets,
        canvas_extents=canvas_extents,
        weight=cr.weight_flat,
        normalizer=normalizer,
        )

    if return_canvas_relative_offsets:
        return render, canvas_relative_offsets
    else:
        return render


def plot_rectangular_pair(
        image_a:MISImage,
        image_b:MISImage,
        relation:tuple[int,int],
        weight=cr.weight_flat,
        focus_overlap=False,
        focus_expand=50
        ):
    render, canvas_relative_offsets=render_rectangular_pair(
        image_a=image_a,
        image_b=image_b,
        relation=relation,
        weight=weight,
        return_canvas_relative_offsets=True)
    plt.imshow(render)
    if focus_overlap:
        a_spans,b_spans=overlap_spans(
            offset_vector=relation,
            a_shape=image_a.shape,
            b_shape=image_b.shape)
        plt.xlim(
            left=canvas_relative_offsets[image_a.name][0]+a_spans[0][0]-focus_expand,
            right=canvas_relative_offsets[image_a.name][0]+a_spans[0][1]+focus_expand)
        plt.ylim(
            top=canvas_relative_offsets[image_a.name][1]+a_spans[1][0]-focus_expand,
            bottom=canvas_relative_offsets[image_a.name][1]+a_spans[1][1]+focus_expand)

def plot_grid_difference_gradient_analysis(
        image_a:MISImage,
        image_b:MISImage,
        dga_grid_result:dict,
        figwidth=12,
        figheight=4,
        overlays=True
        ):
    if "initial_offset" in dga_grid_result:
        fig,axs=plt.subplot_mosaic(
            mosaic=[
                ["dga_map","initial"],
                ["dga_map","optimized"]])
    else:
        fig,axs=plt.subplot_mosaic(
            mosaic=[
                ["dga_map","optimized"]])
    fig.set_figwidth(figwidth)
    fig.set_figheight(figheight)
    plt.tight_layout(pad=1.5,h_pad=2,w_pad=2)

    plt.sca(axs["dga_map"])
    plt.title("Difference Gradient Analysis")
    plot_grid_result(
        dga_grid_results=dga_grid_result,
        overlays=overlays)

    if "initial_offset" in dga_grid_result:
        plt.sca(axs["initial"])
        plt.title("Initial Flat Blend")
        plot_rectangular_pair(
            image_a=image_a,
            image_b=image_b,
            relation=dga_grid_result["initial_offset"],
            weight=cr.weight_dfe,
            focus_overlap=True)

    plt.sca(axs["optimized"])
    plt.title("Optimized Flat Blend")
    plot_rectangular_pair(
        image_a=image_a,
        image_b=image_b,
        relation=dga_grid_result["optimized_offset"],
        weight=cr.weight_dfe,
        focus_overlap=True)